#!/bin/sh
#
eget dnote/dnote
eget naggie/dstask
eget ClementTsang/bottom
eget jesseduffield/lazygit
eget rclone/rclone
eget achannarasappa/ticker
eget dipu-bd/lightnovel-crawler
eget spotDL/spotify-downloader
eget lutris/lutris
