#!/bin/sh
# Install
LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

# Uninstall
bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh

