# Nord Theme for Alacritty

# The Nord color scheme is defined by these specific colors
# Background should be #2E3440 (deep blue-gray)

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

# Added explicit cursor colors to match theme
[colors.cursor]
cursor = "#D8DEE9"
text = "#2E3440"
