version: '3.3'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/radarr:/config
      - ${ROOT}/movies:/movies
      - ${ROOT}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media-net

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${ROOT}/tv:/tv
      - ${ROOT}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media-net

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media-net

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=000
      - DELUGE_LOGLEVEL=error
    volumes:
      - ${CONFIG}/deluge:/config
      - ${ROOT}/downloads:/downloads
    ports:
      - 8112:8112
    restart: unless-stopped
    networks:
      - media-net

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${CONFIG}/plex:/config
      - ${ROOT}/movies:/movies
      - ${ROOT}/tv:/tv
    restart: unless-stopped

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/readarr:/config
      - ${ROOT}/books:/books
      - ${ROOT}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - media-net

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v1.2.9
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - media-net

networks:
  media-net:
    driver: bridge
